#!/usr/bin/env bash
# Installs nginx on server web-01 with requirements:
#       Nginx should be listening on port 80
#       When querying Nginx at its root / with a GET request (requesting a page)
#       using curl, it must return a page that contains the string Hello World!

apt-get update
apt-get -y install nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html;
}
" > /etc/nginx/sites-available/default

service nginx restart
