#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page
# The redirection must be a “301 Moved Permanently”
# Based on nginx installation script

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
replacement_string="server_name _;\n\trewrite^/redirect_me/$ $link permanent;"
sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-available/default
service nginx restart
