#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page
# The redirection must be a “301 Moved Permanently”
# Based on nginx installation script

sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
replacement_string="\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "/^\tlocation \// i\ $replacement_string" /etc/nginx/sites-available default
sudo service nginx restart
