#!/usr/bin/env bash
# Configures an Nginx server to have a custom 404 page:
# that contains the string Ceci n'est pas une page
# The page must return an HTTP 404 error code
# Use redirection script above

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
replacement_string="server_name _;\n\trewrite^/redirect_me/$ $link permanent;"
sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/index.html
replacement_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sed -i "s/listen 80 default_server;/$replacement_string/" /etc/nginx/sites-enabled/default

service nginx restart
