#!/usr/bin/env bash
# Configures an Nginx server to have a custom 404 page:
# that contains the string Ceci n'est pas une page
# The page must return an HTTP 404 error code
# Use redirection script above

new_conf="server_name _;\n\trewrite ^/redirect_me/$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

error_code="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sed -i "s|server_name\ _;|$new_conf|" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sed -i "s/listen 80 default_server;/$error_code/" /etc/nginx/sites-available/default
service nginx restart
