#!/usr/bin/env bash
# Pings an IP address passed as an argument.
#  Accept string as argument, display *message* if no argument, ping IP 5 times

if [ -z "$1" ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi
