#!/usr/bin/env bash
# Displays the contents of the file /etc/passwd.
#   Displays the username, user id, and Home directory path for the user.

passwd_file="/etc/passwd"
while IFS= read -r passwd
do
	    echo "$passwd" | cut -d":" -f1,3,6
    done < "$passwd_file"
