#!/usr/bin/env bash
# A script that loops from 1 to 10 and displays bad luck, good luck and Best School for the 9th, 8th and other iterations: using while loop

i=1

while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
	echo "bad luck"
    elif [ $i -eq 8 ]
    then
	echo "good luck"
   else
	echo "Best School"
    fi
    ((i++))
done
