#!/usr/bin/env bash
# Displays the content of the current directory in a list format.
# Where only the part of the name after the first dash is displayed.

# Requirements:

# Must use for loop
# Do not display hidden files

list=$(ls)

for i in $list; do
    echo "$i" | cut -d '-' -f2
done
