#!/usr/bin/env bash
# Displays information about the school file.

# Requirements: 

# Use if and else
# Check if the file exits and print: school file exists or ... does not ...
# If file exists, print: school file is empty or ... not ... or ... is a regular file.

if [ -e "school" ]
then
    echo "school file exists"
    if [ -s "school" ]
    then
	echo "school file is not empty"
    else
	echo "school file is empty"
    fi
	
    if [ -f "school" ]
    then
	echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
